Repository PrestaShop/hummingbird, pull requests merged in 2023-06, with the labels that each got.

#508 Show/Hide Password: Accessibility on the button
  src/js/visible-password.ts
  templates/_partials/form-fields.tpl
  templates/customer/password-new.tpl
Labels: QA ✔️

#514 fix: icon color on hover inside hompeage cta
  src/scss/custom/modules/_featuredproducts.scss
Labels: Bug, Home Page, Waiting for QA, QA ✔️, CSS

#501 Several bug fix on cart related with products stock
  src/js/components/useQuantityInput.ts
  src/js/pages/checkout.ts
  templates/checkout/_partials/cart-detailed-actions.tpl
Labels: QA ✔️

#515 Fix: product listing responsive
  src/scss/core/components/product/_product-miniature.scss
  templates/catalog/_partials/miniatures/product.tpl
Labels: Bug, Category Page, Home Page, QA ✔️, CSS, Mobile

#524 Improvement: Rework Hn Structure
  modules/blockwishlist/views/templates/components/modals/add-to-wishlist.tpl
  modules/blockwishlist/views/templates/components/modals/create.tpl
  modules/blockwishlist/views/templates/components/modals/delete.tpl
  modules/blockwishlist/views/templates/components/modals/login.tpl
  modules/blockwishlist/views/templates/components/modals/rename.tpl
  modules/blockwishlist/views/templates/components/modals/share.tpl
  modules/productcomments/views/templates/hook/alert-modal.tpl
  modules/productcomments/views/templates/hook/confirm-modal.tpl
  modules/productcomments/views/templates/hook/post-comment-modal.tpl
  modules/ps_checkpayment/views/templates/hook/payment_return.tpl
  modules/ps_contactinfo/ps_contactinfo-rich.tpl
  modules/ps_facetedsearch/ps_facetedsearch.tpl
  modules/ps_legalcompliance/views/templates/hook/hookDisplayFooter.tpl
  modules/ps_linklist/views/templates/hook/linkblock-column.tpl
  modules/ps_shoppingcart/modal.tpl
  modules/ps_wirepayment/views/templates/hook/payment_return.tpl
  modules/psgdpr/views/templates/front/customerPersonalData.tpl
  src/scss/core/layout/_index.scss
  src/scss/core/layout/_left-column.scss
  src/scss/custom/components/category/_header.scss
  src/scss/custom/modules/_contactinfo.scss
  templates/catalog/_partials/customization-modal.tpl
  templates/catalog/_partials/product-customization-modal.tpl
  templates/catalog/_partials/product-customization.tpl
  templates/catalog/_partials/product-details.tpl
  templates/catalog/listing/product-list.tpl
  templates/catalog/product.tpl
  templates/checkout/_partials/address-selector-block.tpl
  templates/checkout/_partials/order-final-summary-table.tpl
  templates/checkout/_partials/order-final-summary.tpl
  templates/checkout/_partials/steps/addresses.tpl
  templates/checkout/_partials/steps/checkout-step.tpl
  templates/checkout/_partials/steps/unreachable.tpl
  templates/checkout/order-confirmation.tpl
  templates/cms/stores.tpl
  templates/components/page-title-section.tpl
  templates/components/section-title.tpl
  templates/customer/_partials/account-transformation-form.tpl
  templates/customer/_partials/block-address.tpl
  templates/customer/_partials/order-detail-return.tpl
  templates/customer/_partials/order-messages.tpl
  templates/customer/order-detail.tpl
  templates/customer/order-follow.tpl
  templates/customer/order-return.tpl
  templates/customer/order-slip.tpl
  templates/errors/404.tpl
  templates/errors/410.tpl
  templates/errors/not-found.tpl
  templates/index.tpl
Labels: QA ✔️
