Repository PrestaShop/hummingbird, pull requests merged in 2023-05, with the labels that each got.

#493 Url properties fix after removing product in cart
  src/js/components/UseHandleCartAction.ts
  src/js/constants/selectors-map.ts
  src/js/pages/cart.ts
  types/selectors.d.ts
Labels: QA ✔️

#495 Fix : [FO] FILTERING - Resize screen to mobile
  src/js/constants/selectors-map.ts
  src/js/modules/facetedsearch/index.ts
  src/js/responsive-toggler.test.ts
  src/js/responsive-toggler.ts
  types/selectors.d.ts
Labels: Javascript, Category Page, QA ✔️

#496 Fix: [FO]Carrier extra content not work on deliveryFormSelector change
  src/js/constants/events-map.ts
  src/js/constants/selectors-map.ts
  src/js/pages/checkout.ts
  src/scss/core/components/_checkout-steps.scss
  templates/checkout/_partials/steps/shipping.tpl
  types/events.d.ts
  types/selectors.d.ts
  types/useDeliveryOption.d.ts
Labels: Bug, Javascript, Checkout Page, QA ✔️, CSS
