Repository PrestaShop/hummingbird, pull requests merged in 2024-09, with the labels that each got.

#653 Remove meta keywords
  templates/_partials/head.tpl
Labels: Waiting for QA

#654 Use new way to access category images
  templates/catalog/_partials/category-header.tpl
  templates/catalog/_partials/subcategories.tpl
Labels: QA ✔️

#655 chore(deps): upgrade some packages (test for node 20)
  .github/workflows/build.yml
  .github/workflows/cd.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  .github/workflows/typecheck.yml
  .stylelintrc
  README.md
  package-lock.json
  package.json
  src/js/components/usePasswordPolicy.ts
  src/js/components/useQuantityInput.test.ts
  src/js/responsive-toggler.test.ts
Labels: QA ✔️, task, dependencies
