Repository PrestaShop/hummingbird, pull requests merged in 2024-06, with the labels that each got.

#621 Fix: issue-616 and issue-615
  src/js/constants/selectors-map.ts
  src/js/product.ts
  templates/catalog/_partials/product-add-to-cart.tpl
Labels: QA ✔️

#626 Fix: issue-611
  templates/customer/_partials/order-detail-no-return.tpl
Labels: QA ✔️

#630 Fix: issue-491
  src/scss/custom/pages/product/_product.scss
  templates/catalog/_partials/product-discounts.tpl
  templates/catalog/_partials/product-prices.tpl
Labels: QA ✔️

#627 Fix: issue-340
  modules/ps_bestsellers/views/templates/hook/ps_bestsellers.tpl
  modules/ps_categoryproducts/views/templates/hook/ps_categoryproducts.tpl
  modules/ps_crossselling/views/templates/hook/ps_crossselling.tpl
  modules/ps_featuredproducts/views/templates/hook/ps_featuredproducts.tpl
  modules/ps_newproducts/views/templates/hook/ps_newproducts.tpl
  modules/ps_specials/views/templates/hook/ps_specials.tpl
  modules/ps_viewedproduct/views/templates/hook/ps_viewedproduct.tpl
  src/scss/abstract/variables/overrides/_overrides.scss
  src/scss/custom/components/category/_pagination.scss
  templates/_partials/pagination.tpl
  templates/catalog/_partials/product-accessories.tpl
  templates/catalog/_partials/productlist.tpl
  templates/catalog/listing/product-list.tpl
  templates/catalog/listing/search.tpl
Labels: QA ✔️

#635 Fix: issue-582
  templates/customer/_partials/account-transformation-form.tpl
Labels: QA ✔️

#619 Overwriting productListingComments.js with the correct product selector
  config/theme.yml
Labels: QA ✔️

#636 Fix: issue-559
  src/scss/custom/components/product/_product-miniature.scss
  src/scss/custom/pages/product/_product.scss
  templates/catalog/_partials/miniatures/product.tpl
  templates/catalog/_partials/product-variants.tpl
Labels: QA ✔️

#634 Fix: issue-590
  src/js/constants/selectors-map.ts
  src/js/guest-password-toggle.ts
  src/js/theme.ts
  templates/checkout/_partials/customer-form.tpl
  templates/checkout/_partials/steps/personal-information.tpl
Labels: QA ✔️

#638 Fix: issue-522
  src/js/components/UseHandleCartAction.ts
  src/js/constants/selectors-map.ts
  src/scss/core/components/_alert.scss
  templates/checkout/_partials/cart-detailed-product-line.tpl
  templates/checkout/cart.tpl
Labels: QA ✔️

#639 Fix: issue-490
  modules/ps_categorytree/views/templates/hook/ps_categorytree.tpl
  modules/ps_facetedsearch/ps_facetedsearch.tpl
  modules/ps_facetedsearch/views/templates/front/catalog/facets.tpl
  src/js/modules/ps_categorytree.ts
  src/js/theme.ts
  src/scss/core/layout/_left-column.scss
  src/scss/custom/components/category-tree/_category-tree.scss
  src/scss/custom/components/search-filters-modules/_search-filters-modules.scss
  src/scss/custom/components/search-filters/_search-filters.scss
Labels: Waiting for QA

#640 Fix: issue-494
  modules/productcomments/views/templates/hook/alert-modal.tpl
  modules/productcomments/views/templates/hook/confirm-modal.tpl
  modules/productcomments/views/templates/hook/empty-product-comment.tpl
  modules/productcomments/views/templates/hook/post-comment-modal.tpl
  modules/productcomments/views/templates/hook/product-additional-info.tpl
  modules/productcomments/views/templates/hook/product-comment-item-prototype.tpl
  modules/productcomments/views/templates/hook/product-comments-list.tpl
  src/img/small_stars.png
  src/img/stars.png
  src/scss/core/modules/_productcomments.scss
  src/scss/custom/components/category/_pagination.scss
  templates/_partials/pagination.tpl
Labels: QA ✔️, Waiting for wording

#641 Feat: handle scroll offset on anchor links
  src/js/constants/selectors-map.ts
  src/js/helpers/scrollPadding.ts
  src/js/theme.ts
  templates/layouts/layout-both-columns.tpl
Labels: QA ✔️

#632 Fix: issue-567
  src/scss/custom/pages/product/_product.scss
  templates/catalog/_partials/product-cover-thumbnails.tpl
  templates/catalog/product.tpl
Labels: QA ✔️
