Repository PrestaShop/hummingbird, pull requests merged in 2025-06, with the labels that each got.

#698 [Idea] Add the <textarea> element among the available types for the FromField class
  templates/_partials/form-fields.tpl
Labels: QA ✔️

#704 [IMPROVEMENTS - PART 10] Global quality improvement
  config/theme.yml
  modules/contactform/views/templates/widget/contactform.tpl
  modules/ps_contactinfo/ps_contactinfo-rich.tpl
  src/scss/bootstrap/components/_index.scss
  src/scss/bootstrap/components/_labels.scss
  src/scss/error.scss
  src/scss/prestashop/base/_utilities.scss
  src/scss/prestashop/components/_brand.scss
  src/scss/prestashop/components/_sitemap.scss
  src/scss/prestashop/components/_store.scss
  src/scss/prestashop/pages/_order-details.scss
  templates/catalog/_partials/miniatures/brand.tpl
  templates/catalog/_partials/product-add-to-cart.tpl
  templates/catalog/_partials/products-top.tpl
  templates/catalog/brands-suppliers.tpl
  templates/catalog/listing/manufacturer.tpl
  templates/catalog/listing/product-list.tpl
  templates/catalog/listing/search.tpl
  templates/catalog/listing/supplier.tpl
  templates/catalog/manufacturers.tpl
  templates/catalog/suppliers.tpl
  templates/checkout/_partials/order-final-summary.tpl
  templates/checkout/cart.tpl
  templates/cms/_partials/sitemap-nested-list.tpl
  templates/cms/sitemap.tpl
  templates/cms/stores.tpl
  templates/customer/_partials/account-transformation-form.tpl
  templates/customer/authentication.tpl
  templates/customer/guest-login.tpl
  templates/customer/guest-tracking.tpl
  templates/customer/page.tpl
  templates/errors/404.tpl
  templates/errors/maintenance.tpl
  templates/errors/not-found.tpl
  templates/errors/restricted-country.tpl
  templates/layouts/layout-error.tpl
Labels: Waiting for wording

#706 [IMPROVEMENTS - PART 12] Global quality improvement
  modules/blockwishlist/views/templates/components/modals/add-to-wishlist.tpl
  modules/ps_banner/ps_banner.tpl
  modules/ps_imageslider/views/templates/hook/slider.tpl
  preview.png
  src/scss/bootstrap/components/_carousel.scss
  src/scss/bootstrap/overrides/variables/_variables-dark.scss
  src/scss/bootstrap/overrides/variables/_variables.scss
  src/scss/bootstrap/overrides/variables/components/_carousel.scss
  src/scss/prestashop/components/product/_product-miniature.scss
  src/scss/vendors/bootstrap/_index.scss
  templates/_partials/pagination.tpl
  templates/catalog/_partials/miniatures/product.tpl
  templates/catalog/_partials/product-prices.tpl
  templates/checkout/_partials/modal-terms.tpl
  templates/checkout/order-confirmation.tpl
  templates/components/page-loader.tpl
Labels: Waiting for QA

#713 [IMPROVEMENTS - PART 15] Global quality improvement
  .github/workflows/build.yml
  README.md
  webpack/.env-docker-example
  webpack/.env-example
  webpack/.env-no-vhost-example
  webpack/.env-vhost-example
  webpack/webpack.parts.js
Labels: Waiting for QA

#712 Add an attribute minlength if provided
  templates/_partials/form-fields.tpl
Labels: QA ✔️

#723 [IMPROVEMENTS - PART 17] Global quality improvement
  src/scss/prestashop/components/_order-confirmation.scss
  src/scss/prestashop/components/checkout/_checkout-final-summary.scss
  src/scss/prestashop/components/checkout/_index.scss
  templates/catalog/_partials/product-customization.tpl
  templates/checkout/_partials/order-confirmation-table.tpl
  templates/checkout/_partials/order-final-summary-table.tpl
  templates/checkout/_partials/order-final-summary.tpl
  templates/checkout/_partials/steps/payment.tpl
Labels: Waiting for wording

#727 Add contributors
  config/theme.yml
Labels: Waiting for QA
