Repository PrestaShop/hummingbird, pull requests merged in 2025-09, with the labels that each got.

#761 [ACCESSIBILITY - PART 4] Login page + form + password
  src/js/constants/selectors-map.ts
  src/js/form-validation.ts
  src/js/visible-password.ts
  src/scss/bootstrap/components/_labels.scss
  templates/_partials/form-errors.tpl
  templates/_partials/form-fields.tpl
  templates/customer/_partials/address-form.tpl
  templates/customer/_partials/customer-form.tpl
  templates/customer/_partials/login-form.tpl
  templates/customer/authentication.tpl
  templates/customer/password-email.tpl
  templates/customer/password-infos.tpl
  templates/customer/password-new.tpl
Labels: QA ✔️, Waiting for wording

#722 refactor: remove <style> section and use bootstrap class instead
  modules/contactform/views/templates/widget/contactform.tpl
  templates/customer/order-detail.tpl
Labels: QA ✔️

#763 [A11Y][ps_contactinfo] improve accessibility
  modules/ps_contactinfo/nav.tpl
  modules/ps_contactinfo/ps_contactinfo-rich.tpl
  modules/ps_contactinfo/ps_contactinfo.tpl
Labels: Module, QA ✔️, Refactoring, Accessibility, Waiting for wording

#767 [A11Y][ps_imageslider] Improve accessibility
  modules/ps_imageslider/views/templates/hook/slider.tpl
  src/scss/bootstrap/components/_carousel.scss
  src/scss/bootstrap/overrides/variables/components/_carousel.scss
Labels: QA ✔️

#768 [A11Y][ps_categorytree] Improve Accessibility
  modules/ps_categorytree/views/templates/hook/ps_categorytree.tpl
Labels: Module, QA ✔️, Refactoring, Accessibility, Waiting for author

#769 [A11Y][ps_searchbar] improve accessibility
  modules/ps_searchbar/ps_searchbar.tpl
  src/js/constants/selectors-map.ts
  src/js/modules/ps_searchbar.ts
  src/js/services/search.ts
  src/scss/prestashop/modules/_searchbar.scss
Labels: Module, QA ✔️, Accessibility, Waiting for author, Waiting for wording

#774 Accessibility Improvements on Contact Us Page
  modules/contactform/views/templates/widget/contactform.tpl
Labels: QA ✔️, Refactoring, Improvement, Accessibility, Waiting for wording

#773 Allow footer blocks to be closed with keyboard on small devices
  modules/ps_contactinfo/ps_contactinfo.tpl
  modules/ps_customeraccountlinks/ps_customeraccountlinks.tpl
  modules/ps_linklist/views/templates/hook/linkblock.tpl
  src/scss/prestashop/layout/_footer.scss
Labels: QA ✔️, Refactoring, Improvement, Accessibility, Mobile, Waiting for wording
